using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SAMS.Models.Help;

namespace SAMS.Controllers
{
	[Authorize]
	public class HelpController(UserManager<ApplicationUser> userManager) : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager = userManager;

		[HttpGet]
		public async Task<IActionResult> Index()
		{
			var user = await _userManager.GetUserAsync(User).ConfigureAwait(true);
			if (user is null)
			{
				return Challenge();
			}

			var roles = await _userManager.GetRolesAsync(user).ConfigureAwait(true);
			var roleSet = new HashSet<string>(roles, StringComparer.OrdinalIgnoreCase);
			var sections = BuildSections(roleSet);

			var model = new HelpPageViewModel
			{
				DisplayName = user.FullName,
				GeneratedAtUtc = DateTime.UtcNow,
				Sections = sections
			};

			return View(model);
		}

		private static IReadOnlyList<RoleHelpSection> BuildSections(IReadOnlySet<string> roleSet)
		{
			var sections = new List<RoleHelpSection>
			{
				new()
				{
					RoleName = "All Authenticated Users",
					Summary = "Core application behavior available once signed in.",
					AllowedBehaviors =
					[
						"Use role-specific pages that your assigned roles permit.",
						"Submit role-scoped error reports through in-app error endpoints.",
						"Receive standardized system error responses with traceable SAMS error codes for unexpected failures."
					],
					NotAllowedBehaviors =
					[
						"Access features gated by roles you do not have.",
						"Assume background automation can be bypassed; attendance transitions still follow schedule and timing rules."
					]
				}
			};

			if (roleSet.Contains("Student"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "Student",
					Summary = "Scan attendance for current bell and receive immediate status feedback.",
					AllowedBehaviors =
					[
						"Use Student Scan to submit classroom QR attendance during valid bell windows.",
						"Receive present/tardy outcomes based on schedule timing and configured grace periods.",
						"View role-specific error guidance when scan prerequisites are not met."
					],
					NotAllowedBehaviors =
					[
						"Modify other students' attendance records.",
						"Override schedule, room QR, or semester mapping configuration."
					]
				});
			}

			if (roleSet.Contains("Teacher"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "Teacher",
					Summary = "View bell roster membership and attendance states for assigned courses.",
					AllowedBehaviors =
					[
						"Open Teacher Roster views for bell-based student lists.",
						"See daily and bell attendance statuses for students associated with your course assignments.",
						"Submit teacher-scoped automated error reports when workflow issues occur."
					],
					NotAllowedBehaviors =
					[
						"Edit global role assignments or system-wide schedule configuration.",
						"Access account-management workflows reserved for administrative roles."
					]
				});
			}

			if (roleSet.Contains("Synnovation Lab QR Code Scanner Management"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "Synnovation Lab QR Code Scanner Management",
					Summary = "Operate Class Kiosk authentication and attendance/location updates.",
					AllowedBehaviors =
					[
						"Use Class Kiosk scanner + PIN intake flow for student check-ins.",
						"Trigger bell/daily attendance updates and location updates when validation succeeds.",
						"Use kiosk-specific error reporting endpoints for operational issues."
					],
					NotAllowedBehaviors =
					[
						"Bypass student credential, scanner, or room mapping checks.",
						"Perform administrative account lifecycle actions unless separately assigned admin roles."
					]
				});
			}

			if (roleSet.Contains("Attendance Office Member"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "Attendance Office Member",
					Summary = "Operate attendance-office scoped support and error-reporting flows.",
					AllowedBehaviors =
					[
						"Access attendance-office area error-reporting endpoint behavior.",
						"Review system outcomes generated by attendance scan and automation workflows.",
						"Escalate data-quality or processing issues with standardized references."
					],
					NotAllowedBehaviors =
					[
						"Use account-management endpoints reserved for school/systems admin roles.",
						"Alter restricted role memberships without corresponding admin roles."
					]
				});
			}

			if (roleSet.Contains("Admin"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "Admin",
					Summary = "Work with report/case views and admin-scoped error processing.",
					AllowedBehaviors =
					[
						"Open report index, details, and case list JSON endpoints.",
						"Review self-created and global report entries made available in report workflows.",
						"Use admin area automated error reporting."
					],
					NotAllowedBehaviors =
					[
						"Assume all admin controllers are strictly role-locked where authorization attributes are not enforced in source.",
						"Override security constraints of higher-privilege identity flows without proper role assignment."
					]
				});
			}

			if (roleSet.Contains("HS School Admin") || roleSet.Contains("Synnovation Lab Admin") || roleSet.Contains("District Admin"))
			{
				sections.Add(new RoleHelpSection
				{
					RoleName = "HS School Admin / Synnovation Lab Admin / District Admin",
					Summary = "Manage user account lifecycle and profile-role metadata workflows.",
					AllowedBehaviors =
					[
						"Use account-management actions such as details, create, edit, and delete where role attributes are applied.",
						"Manage role-aligned account fields used by attendance and roster features.",
						"Troubleshoot account-level issues via standardized error routing and reports."
					],
					NotAllowedBehaviors =
					[
						"Treat commented authorization as enforced security.",
						"Skip validation requirements for identifiers and profile fields required by downstream attendance features."
					]
				});
			}

			return sections;
		}
	}
}
